name: "Full CI"
on:
  push:
    branches:
      - dev
      - release-*
      - refs/tags/*

    ##############################################################################
    #                                                                            #
    #    These sections must be synchronized with 'paths' in full-ci-dummy.yml   #
    #                                                                            #
    ##############################################################################

  pull_request:
    branches:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string
    paths-ignore:
      - '.github/workflows/quarto-render.yml'
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'
      - 'tiledb/doxygen/source/*'
      - 'tiledb/sm/c_api/tiledb_version.h'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

## NOTE: the job ids below must be unique!
jobs:
  ci_mingw_r:
    uses: ./.github/workflows/build-rtools40.yml

#  # dummy job for branch protection check
#  full_ci_passed:
#    needs: [
#        ci1,
#        ci2,
#        ci2,
#        ci3,
#        ci4,
#        ci5,
#        ci6,
#        ci7,
#        ci8,
#        ci9,
#        ci10,
#        ci_msvc,
#        backward_compatibility,
#        standalone
#      ]
#    runs-on: ubuntu-22.04
#    steps:
#      - name: ''
#        run: echo "Complete"
